// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC3olLo2FvBDmhJ62VVzA9OL3ZBDfLIpc',
    appId: '1:645903648310:web:30224f86306a2cad3fba97',
    messagingSenderId: '645903648310',
    projectId: 'uas-19312078',
    authDomain: 'uas-19312078.firebaseapp.com',
    storageBucket: 'uas-19312078.appspot.com',
    measurementId: 'G-QHD3ZT5KKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4C7wk06eXkSp7tBzEKp7tsbG_gtGZaNI',
    appId: '1:645903648310:android:a8fda553a77d29e73fba97',
    messagingSenderId: '645903648310',
    projectId: 'uas-19312078',
    storageBucket: 'uas-19312078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBehd3QPAKl7A_DaWBT-MeGje0AlPLshy4',
    appId: '1:645903648310:ios:33365e26b2fd42d93fba97',
    messagingSenderId: '645903648310',
    projectId: 'uas-19312078',
    storageBucket: 'uas-19312078.appspot.com',
    iosBundleId: 'com.uashafiz.uasHafiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBehd3QPAKl7A_DaWBT-MeGje0AlPLshy4',
    appId: '1:645903648310:ios:eb679a6d16aaad903fba97',
    messagingSenderId: '645903648310',
    projectId: 'uas-19312078',
    storageBucket: 'uas-19312078.appspot.com',
    iosBundleId: 'com.uashafiz.uasHafiz.RunnerTests',
  );
}
